#!/bin/bash

# Copy shortcuts bash file
cp ../s /usr/local/bin

# Copy schelper
mkdir /usr/share/term-shortcuts
cp ../schelper /usr/share/term-shortcuts

# Create config folder
# mkdir ~/.config/term-shortcuts

# echo -e "\nPROMPT_COMMAND='history -a'\n" >> ~/.bashrc
