#!/bin/bash

# Copy shortcuts bash file
cp ../s /usr/local/bin

# Copy schelper
mkdir /usr/share/term-shortcuts
cp ../schelper /usr/share/term-shortcuts

# Create config folder
# mkdir ~/.config/term-shortcuts

# Bash alias
# Add "alias s='source s'" to .bashrc
echo -e "\nalias s='source s'\n" >> ~/.bashrc
