#!/bin/bash

# Remove bash file
rm /usr/local/bin/s

# Remove schelper
rm -r /usr/share/term-shortcuts

# Remove config file
# rm ~/.config/term-shortcuts

# Remove from .bashrc
sed '/#Alias for term-shortcuts/d' ~/.bashrc > /tmp/new-bashrc
cat /tmp/new-bashrc > ~/.bashrc
sed '/alias s='\''source s'\''/d' ~/.bashrc > /tmp/new-bashrc
cat /tmp/new-bashrc > ~/.bashrc